from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel

from database import SessionLocal
from models import Student, StudentInterest, QuizAnswer

from ai_student.llm.service import generate_next_question
from ai_student.quiz.question_engine import validate_question

router = APIRouter(
    prefix="/api/students",
    tags=["Interest+"]
)


# ============================================================
# DATABASE DEPENDENCY
# ============================================================

def get_db():
    db = SessionLocal()

    try:
        yield db
    finally:
        db.close()


# ============================================================
# REQUEST SCHEMAS
# ============================================================

class InterestRequest(BaseModel):
    interest: str


class AnswerRequest(BaseModel):
    interest: str
    question_id: str
    question: str
    answer: str
    question_order: int


# ============================================================
# CHECK INTEREST+ STATUS
# ============================================================

@router.get("/{student_id}/interests/status")
def get_interest_status(
    student_id: str,
    db: Session = Depends(get_db)
):

    interests = (
        db.query(StudentInterest)
        .filter(
            StudentInterest.student_id == student_id
        )
        .all()
    )

    if not interests:
        return {
            "student_id": student_id,
            "completed": False,
            "interests": []
        }

    return {
        "student_id": student_id,
        "completed": True,
        "interests": [
            {
                "interest": interest.interest,
                "status": interest.status
            }
            for interest in interests
        ]
    }


# ============================================================
# SAVE NEW INTEREST
# ============================================================

@router.post("/{student_id}/interests")
def add_interest(
    student_id: str,
    interest_data: InterestRequest,
    db: Session = Depends(get_db)
):

    # Check student exists
    student = (
        db.query(Student)
        .filter(
            Student.student_id == student_id
        )
        .first()
    )

    if not student:
        raise HTTPException(
            status_code=404,
            detail="Student not found"
        )

    # Check whether this interest already exists
    existing_interest = (
        db.query(StudentInterest)
        .filter(
            StudentInterest.student_id == student_id,
            StudentInterest.interest == interest_data.interest
        )
        .first()
    )

    if existing_interest:
        return {
            "message": "Interest already exists",
            "student_id": student_id,
            "interest": existing_interest.interest,
            "status": existing_interest.status
        }

    new_interest = StudentInterest(
        student_id=student_id,
        interest=interest_data.interest,
        status="active"
    )

    db.add(new_interest)
    db.commit()
    db.refresh(new_interest)

    return {
        "message": "Interest saved successfully",
        "student_id": student_id,
        "interest": new_interest.interest,
        "status": new_interest.status
    }


# ============================================================
# START INTEREST+ SESSION
# ============================================================

@router.post("/{student_id}/interest-session/start")
def start_interest_session(
    student_id: str,
    interest_data: InterestRequest,
    db: Session = Depends(get_db)
):

    # --------------------------------------------------------
    # 1. Check whether student exists
    # --------------------------------------------------------

    student = (
        db.query(Student)
        .filter(
            Student.student_id == student_id
        )
        .first()
    )

    if not student:
        raise HTTPException(
            status_code=404,
            detail="Student not found"
        )

    # --------------------------------------------------------
    # 2. Get previous answers for this interest
    # --------------------------------------------------------

    previous_answers = (
        db.query(QuizAnswer)
        .filter(
            QuizAnswer.student_id == student_id,
            QuizAnswer.interest == interest_data.interest
        )
        .order_by(
            QuizAnswer.question_order
        )
        .all()
    )

    # --------------------------------------------------------
    # 3. Build conversation for the AI
    #
    # IMPORTANT:
    # Use the REAL question_id generated by the AI.
    # Do NOT create q0, q1, q2 manually.
    # --------------------------------------------------------

    conversation = [
        {
            "question_id": answer.question_id,
            "question": answer.question,
            "answer": answer.answer
        }
        for answer in previous_answers
    ]

    # --------------------------------------------------------
    # 4. Ask AI for the next question
    # --------------------------------------------------------

    question = generate_next_question(
        interest=interest_data.interest,
        conversation=conversation,
        existing_skills=[],
        previous_interests=[]
    )

    # --------------------------------------------------------
    # 5. AI says assessment is complete
    # --------------------------------------------------------

    if question is None:

        return {
            "completed": True,
            "next_question": None
        }

    # --------------------------------------------------------
    # 6. Validate AI-generated question
    # --------------------------------------------------------

    question = validate_question(question)

    return {
        "completed": False,
        "next_question": question.model_dump()
    }


# ============================================================
# SUBMIT ANSWER + GENERATE NEXT QUESTION
# ============================================================

@router.post("/{student_id}/interest-session/answer")
def submit_interest_answer(
    student_id: str,
    answer_data: AnswerRequest,
    db: Session = Depends(get_db)
):

    # --------------------------------------------------------
    # 1. Check whether student exists
    # --------------------------------------------------------

    student = (
        db.query(Student)
        .filter(
            Student.student_id == student_id
        )
        .first()
    )

    if not student:
        raise HTTPException(
            status_code=404,
            detail="Student not found"
        )

    # --------------------------------------------------------
    # 2. Save student's answer
    # --------------------------------------------------------

    new_answer = QuizAnswer(
        student_id=student_id,
        interest=answer_data.interest,
        question_id=answer_data.question_id,
        question=answer_data.question,
        answer=answer_data.answer,
        question_order=answer_data.question_order
    )

    db.add(new_answer)
    db.commit()
    db.refresh(new_answer)

    # --------------------------------------------------------
    # 3. Get ALL previous answers for this interest
    # --------------------------------------------------------

    previous_answers = (
        db.query(QuizAnswer)
        .filter(
            QuizAnswer.student_id == student_id,
            QuizAnswer.interest == answer_data.interest
        )
        .order_by(
            QuizAnswer.question_order
        )
        .all()
    )

    # --------------------------------------------------------
    # 4. Build conversation for AI
    # --------------------------------------------------------

    conversation = [
        {
            "question_id": answer.question_id,
            "question": answer.question,
            "answer": answer.answer
        }
        for answer in previous_answers
    ]

    # --------------------------------------------------------
    # 5. Ask AI for next question
    # --------------------------------------------------------

    next_question = generate_next_question(
        interest=answer_data.interest,
        conversation=conversation,
        existing_skills=[],
        previous_interests=[]
    )

    # --------------------------------------------------------
    # 6. Quiz completed
    # --------------------------------------------------------

    if next_question is None:

        return {
            "completed": True,
            "next_question": None,
            "message": "Interest+ assessment completed."
        }

    # --------------------------------------------------------
    # 7. Validate AI-generated question
    # --------------------------------------------------------

    next_question = validate_question(next_question)

    return {
        "completed": False,
        "next_question": next_question.model_dump()
    }