from sqlalchemy import Column, Integer, String, Float, Text
from database import Base,engine
Base.metadata.create_all(bind=engine)

# ============================================================
# USER
# ============================================================

class User(Base):
    __tablename__ = "users"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    user_id = Column(
        String,
        unique=True,
        nullable=False,
        index=True
    )

    full_name = Column(
        String,
        nullable=False
    )

    password_hash = Column(
        String,
        nullable=False
    )

    role = Column(
        String,
        nullable=False
    )


# ============================================================
# STUDENT
# ============================================================

class Student(Base):
    __tablename__ = "students"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    student_id = Column(
        String,
        unique=True,
        nullable=False,
        index=True
    )

    name = Column(
        String,
        nullable=False
    )

    roll_number = Column(
        String,
        nullable=False
    )

    attendance = Column(
        Integer,
        
        nullable=False
    )

    previous_sem_cgpa = Column(
        Float,
        nullable=False
    )

    extracurricular_count = Column(
        Integer,
        nullable=False
    )


# ============================================================
# STUDENT INTEREST
# ============================================================

class StudentInterest(Base):
    __tablename__ = "student_interests"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    student_id = Column(
        String,
        nullable=False,
        index=True
    )

    interest = Column(
        String,
        nullable=False
    )

    status = Column(
        String,
        nullable=False,
        default="active"
    )


# ============================================================
# QUIZ ANSWER
# ============================================================

class QuizAnswer(Base):
    __tablename__ = "quiz_answers"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    student_id = Column(
        String,
        nullable=False,
        index=True
    )

    interest = Column(
        String,
        nullable=False,
        index=True
    )

    # IMPORTANT:
    # This stores the actual question_id generated by the AI.
    #
    # Example:
    # q1_interest_level
    # speaking_experience
    # q5_marketing_specific_aspect
    question_id = Column(
        String,
        nullable=False,
        index=True
    )

    # Actual question shown to the student.
    question = Column(
        Text,
        nullable=False
    )

    # Stored as TEXT because AI questions can accept:
    #
    # - scale answers
    # - single choice
    # - multiple choice
    # - text answers
    #
    # The API converts the answer to JSON before storing it.
    answer = Column(
        Text,
        nullable=False
    )

    # Used only to preserve the order in which
    # questions were answered.
    question_order = Column(
        Integer,
        nullable=False
    )


# ============================================================
# INTEREST ANALYSIS
# ============================================================

class InterestAnalysis(Base):
    __tablename__ = "interest_analysis"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    student_id = Column(
        String,
        nullable=False,
        index=True
    )

    interest = Column(
        String,
        nullable=False,
        index=True
    )

    # --------------------------------------------------------
    # Scores generated/calculated by the Interest+ system
    # --------------------------------------------------------

    interest_score = Column(
        Float,
        nullable=True
    )

    confidence_score = Column(
        Float,
        nullable=True
    )

    experience_score = Column(
        Float,
        nullable=True
    )

    capability_score = Column(
        Float,
        nullable=True
    )

    # --------------------------------------------------------
    # AI-generated analysis
    #
    # These are stored as text for now.
    #
    # Later, if required, we can create separate tables
    # for skill gaps, directions, strengths, etc.
    # --------------------------------------------------------

    strengths = Column(
        Text,
        nullable=True
    )

    skill_gaps = Column(
        Text,
        nullable=True
    )

    potential_directions = Column(
        Text,
        nullable=True
    )

    next_steps = Column(
        Text,
        nullable=True
    )

    evidence = Column(
        Text,
        nullable=True
    )

    summary = Column(
        Text,
        nullable=True
    )

    # Optional raw/general analysis field.
    # Useful for debugging or storing additional AI output.
    analysis = Column(
        Text,
        nullable=True
    )


# ============================================================
# CAREER PIVOT / SKILL GAP & ROADMAP ANALYSIS
# ============================================================

class CareerPivotAnalysis(Base):
    __tablename__ = "career_pivot_analyses"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    student_id = Column(
        String,
        nullable=False,
        index=True
    )

    interest = Column(
        String,
        nullable=False,
        index=True
    )

    direction = Column(
        String,
        nullable=False,
        index=True
    )

    # Industry required skills for this direction (JSON)
    required_skills = Column(
        Text,
        nullable=True
    )

    # Student skill assessments (JSON)
    skill_assessments = Column(
        Text,
        nullable=True
    )

    # Transferable skills identified (JSON)
    transferable_skills = Column(
        Text,
        nullable=True
    )

    # Skill gaps (JSON)
    skill_gaps = Column(
        Text,
        nullable=True
    )

    # Transition difficulty: low, moderate, high
    transition_difficulty = Column(
        String,
        nullable=True
    )

    # Transition rationale / explanation
    transition_reason = Column(
        Text,
        nullable=True
    )

    # Step-by-step personalized learning roadmap (JSON)
    roadmap = Column(
        Text,
        nullable=True
    )