from typing import Any, Dict, List

from pydantic import BaseModel, Field


# ============================================================
# INPUT SCHEMA
# ============================================================

class InterestAnalysisInput(BaseModel):
    """
    Information provided to the AI for analyzing
    a student's interest.
    """

    interest: str = Field(
        description="The student's current interest being analyzed."
    )

    answers: List[Dict[str, Any]] = Field(
        description=(
            "Answers collected from the student's adaptive "
            "interest-discovery questions."
        )
    )

    existing_skills: List[str] = Field(
        default_factory=list,
        description="Skills currently known or reported for the student."
    )

    previous_interests: List[str] = Field(
        default_factory=list,
        description="Interests explored previously."
    )


# ============================================================
# ADAPTIVE QUESTION OUTPUT
# ============================================================

class GeneratedQuestion(BaseModel):
    """
    A question dynamically generated by the LLM.
    """

    completed: bool = Field(
        default=False,
        description=(
            "True when the AI has enough information "
            "and the quiz should end."
        )
    )

    question_id: str | None = Field(
        default=None,
        description="Unique identifier for the generated question."
    )

    question: str | None = Field(
        default=None,
        description="Question shown to the student."
    )

    response_type: str | None = Field(
        default=None,
        description=(
            "Allowed values: scale, single_choice, "
            "multiple_choice, text."
        )
    )

    options: List[str] | None = Field(
        default=None,
        description=(
            "Options for scale, single_choice or "
            "multiple_choice questions."
        )
    )


# ============================================================
# FINAL INTEREST ANALYSIS OUTPUT
# ============================================================

class InterestAnalysis(BaseModel):
    """
    Structured analysis generated by the AI.
    """

    interest: str

    interest_score: int = Field(
        ge=0,
        le=100
    )

    confidence_score: int = Field(
        ge=0,
        le=100
    )

    experience_score: int = Field(
        ge=0,
        le=100
    )

    capability_score: int = Field(
        ge=0,
        le=100
    )

    strengths: List[str]

    skill_gaps: List[str]

    potential_directions: List[str]

    next_steps: List[str]

    evidence: List[str]

    summary: str