from typing import Any, Dict, List

from pydantic import BaseModel, Field


# ============================================================
# INPUT SCHEMA
# ============================================================

class InterestAnalysisInput(BaseModel):
    """
    Information provided to the AI for analyzing a student's interest.
    """

    interest: str = Field(
        description="The student's current interest being analyzed."
    )

    answers: List[Dict[str, Any]] = Field(
        description=(
            "Answers collected from the student's adaptive "
            "interest-discovery questions."
        )
    )

    existing_skills: List[str] = Field(
        default_factory=list,
        description=(
            "Skills currently known or reported for the student."
        )
    )

    previous_interests: List[str] = Field(
        default_factory=list,
        description=(
            "Interests that the student has explored previously."
        )
    )


# ============================================================
# OUTPUT SCHEMA
# ============================================================

class InterestAnalysis(BaseModel):
    """
    Structured analysis generated by the AI.
    """

    interest: str = Field(
        description="The student's main interest being analyzed."
    )

    interest_score: int = Field(
        ge=0,
        le=100,
        description=(
            "Strength of the student's interest from 0 to 100."
        )
    )

    confidence_score: int = Field(
        ge=0,
        le=100,
        description=(
            "The student's confidence in their current ability "
            "related to this interest, from 0 to 100."
        )
    )

    experience_score: int = Field(
        ge=0,
        le=100,
        description=(
            "The student's level of practical exposure or "
            "experience in this interest, from 0 to 100."
        )
    )

    capability_score: int = Field(
        ge=0,
        le=100,
        description=(
            "Estimated current capability of the student in "
            "this interest area, from 0 to 100."
        )
    )

    strengths: List[str] = Field(
        description=(
            "Strengths demonstrated by the student that are "
            "relevant to the interest."
        )
    )

    skill_gaps: List[str] = Field(
        description=(
            "Skills or capabilities the student may need "
            "to develop."
        )
    )

    potential_directions: List[str] = Field(
        description=(
            "Areas, activities, roles, or directions that "
            "are worth exploring based on the student's profile."
        )
    )

    next_steps: List[str] = Field(
        description=(
            "Practical actions the student can take to explore "
            "or develop this interest."
        )
    )

    evidence: List[str] = Field(
        description=(
            "Evidence from the student's responses supporting "
            "the analysis."
        )
    )

    summary: str = Field(
        description=(
            "A short, student-friendly explanation of the analysis."
        )
    )