from typing import Any

from pydantic import BaseModel, Field


# ============================================================
# QUIZ ANSWER
# ============================================================

class QuizAnswer(BaseModel):
    """
    A single answer provided by the student.
    """

    question_id: str = Field(
        description="Unique identifier of the question."
    )

    question: str = Field(
        description="The question shown to the student."
    )

    answer: Any = Field(
        description="The student's answer."
    )


# ============================================================
# QUIZ SESSION
# ============================================================

class QuizSession(BaseModel):
    """
    Current state of an interest-discovery session.
    """

    interest: str = Field(
        description="Interest currently being explored."
    )

    answers: list[QuizAnswer] = Field(
        default_factory=list,
        description="Answers collected during the session."
    )

    completed: bool = Field(
        default=False,
        description="Whether the adaptive quiz is complete."
    )


# ============================================================
# INTEREST ANALYSIS OUTPUT
# ============================================================

class InterestAnalysis(BaseModel):
    """
    Structured analysis generated by the AI after
    evaluating the student's interest-discovery session.
    """

    interest: str = Field(
        description="The student's main interest being analyzed."
    )

    interest_score: int = Field(
        ge=0,
        le=100,
        description="Strength of the student's interest from 0 to 100."
    )

    confidence_score: int = Field(
        ge=0,
        le=100,
        description="The student's confidence in their current ability from 0 to 100."
    )

    experience_score: int = Field(
        ge=0,
        le=100,
        description="The student's practical experience in the area from 0 to 100."
    )

    capability_score: int = Field(
        ge=0,
        le=100,
        description="The student's current demonstrated capability from 0 to 100."
    )

    strengths: list[str] = Field(
        description="Relevant strengths demonstrated by the student."
    )

    skill_gaps: list[str] = Field(
        description="Skills or capabilities that may need development."
    )

    potential_directions: list[str] = Field(
        description="Areas, activities, roles, or directions worth exploring."
    )

    next_steps: list[str] = Field(
        description="Practical actions the student can take next."
    )

    evidence: list[str] = Field(
        description="Specific evidence from the student's answers or profile."
    )

    summary: str = Field(
        description="Short, student-friendly explanation of the analysis."
    )